# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Plugin-Connection
version:      1.00
version_from: lib/Class/DBI/Plugin/Connection.pm
installdirs:  site
requires:
    Class::DBI:                    0.93

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.29
